Proyecto DSW2 /config/routes.rb
Rails.application.routes.draw do
  resources :ingredients
  resources :implements
  resources :recipes do
    resources :comments, only: [:create, :destroy, :update]
  end

  get 'welcome/index'

  devise_for :users
  resources :highs
  get 'search_recipe/index'

  get 'search_recipe/search_form'
  get 'searchrecipe/search'
  get 'searchrecipe/search_form'
  get 'searchrecipe/index'
  get 'searchrecipe/search'
  get 'searchrecipe/search_form'

  root 'welcome#index'

  get "/dashboard", to: "welcome#dashboard"
  get "/aceptarimp", to: "welcome#aceptarimp"
  get "/aceptaring", to: "welcome#aceptaring"

  put "/recipes/:id/publish", to: "recipes#publish"
  put "/implements/:id/publish", to: "implements#publish"
  put "/ingredients/:id/publish", to: "ingredients#publish"

  get "/buscar_receta/index" => "buscar_receta#index"

end

Proyecto DSW2 /app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "CookZilla" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/welcome/index" >CookZilla</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            </li>

            <% if user_signed_in? && current_user.is_admin? %>
                <li class="col-md">
                  <%= link_to "Aceptar/Añadir Implemento", aceptarimp_path%>
                </li>
                <li class="col-md">
                  <%= link_to "Aceptar/Añadir Ingredientes", aceptaring_path%>
                </li>
                <li class="col-md">
                  <%= link_to "Recetas", recipes_path%>
                </li>
                <li class="col-md">
                  <%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete %>
                </li>
            <% elsif user_signed_in? && current_user.is_moderador? %>
                <li class="col-md">
                  <%= link_to "Moderar Receta", dashboard_path%>
                </li>
                <li class="col-md">
                  <%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete %>
                </li>
            <% elsif user_signed_in? && current_user.is_normal_user? %>
                <li class="col-md">
                  <%= link_to "Crear Receta", recipes_path%>
                </li>
                <li class="col-md">
                  <%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete %>
                </li>
            <% else %>
                <li class="col-md">
                  <%= link_to "Iniciar Sesion", new_user_session_path %>
                </li>
                <li class="col-md">
                  <%= link_to "Crear Cuenta", new_user_registration_path %>
                </li>
            <%end%>

          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Noticias</h3>
            <ul class="nav nav-list">
              <li class="nav-header"></li>
              <li><%= link_to "Link1", "#"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; CookZilla Company 2016 . Todos los derechos reservados</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>