Proyecto DSW2 /config/routes.rb
Rails.application.routes.draw do
  resources :ingredients
  resources :implements
  resources :recipes do
    resources :comments, only: [:create, :destroy, :update]
  end

  get 'welcome/index'

  devise_for :users
  resources :highs
  get 'search_recipe/index'

  get 'search_recipe/search_form'
  get 'searchrecipe/search'
  get 'searchrecipe/search_form'
  get 'searchrecipe/index'
  get 'searchrecipe/search'
  get 'searchrecipe/search_form'

  root 'welcome#index'

  get "/dashboard", to: "welcome#dashboard"
  get "/aceptarimp", to: "welcome#aceptarimp"
  get "/aceptaring", to: "welcome#aceptaring"

  put "/recipes/:id/publish", to: "recipes#publish"
  put "/implements/:id/publish", to: "implements#publish"
  put "/ingredients/:id/publish", to: "ingredients#publish"

  get "/buscar_receta/index" => "buscar_receta#index"

end

Proyecto DSW2 /app/models/implement.rb
class Implement < ActiveRecord::Base
	include AASM
	has_many :recipe_implements
	has_many :recipes, through: :recipe_implementss


    scope :aceptados, ->{where(state: "published")}
    aasm column: "state" do
        state :in_draft, initial: true
        state :published

        event :publish do
            transitions from: :in_draft, to: :published
        end

        event :unpublish do
            transitions from: :published, to: :in_draft
        end
    end
end

Proyecto DSW2 /app/controllers/implements_controller.rb
class ImplementsController < ApplicationController
  before_action :authenticate_user!, except: [:show,:index]
  before_action :authenticate_admin!, only: [:destroy, :edit, :update, :publish]
  before_action :authenticate_normal_user!, only: [:new,:create]
  before_action :set_implement, only: [:show, :edit, :update, :destroy, :publish]

  # GET /implements
  # GET /implements.json
  def index
    if user_signed_in? && current_user.is_admin?
      @implements = Implement.all
    else
      @implements = Implement.aceptados
    end
  end

  # GET /implements/1
  # GET /implements/1.json
  def show
  end

  # GET /implements/new
  def new
    @implement = Implement.new
  end

  # GET /implements/1/edit
  def edit
  end

  def publish
    @implement.publish!
    redirect_to @implement
  end

  # POST /implements
  # POST /implements.json
  def create
    @implement = Implement.new(implement_params)

    respond_to do |format|
      if @implement.save
        format.html { redirect_to @implement, notice: 'Implement was successfully created.' }
        format.json { render :show, status: :created, location: @implement }
      else
        format.html { render :new }
        format.json { render json: @implement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /implements/1
  # PATCH/PUT /implements/1.json
  def update
    respond_to do |format|
      if @implement.update(implement_params)
        format.html { redirect_to @implement, notice: 'Implement was successfully updated.' }
        format.json { render :show, status: :ok, location: @implement }
      else
        format.html { render :edit }
        format.json { render json: @implement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /implements/1
  # DELETE /implements/1.json
  def destroy
    @implement.destroy
    respond_to do |format|
      format.html { redirect_to implements_url, notice: 'Implement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_implement
      @implement = Implement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def implement_params
      params.require(:implement).permit(:nombre)
    end
end

Proyecto DSW2 /app/helpers/implements_helper.rb
module ImplementsHelper
end

Proyecto DSW2 /app/views/implement/_form.html.erb
<%= form_for @implement, :html => { :class => "form-horizontal implement" } do |f| %>

  <% if @implement.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@implement.errors.count, "error") %> prohibited this implement from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @implement.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nombre, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nombre, :class => 'form-control', :required => true %>
    </div>
    <%=f.error_span(:nombre) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                implements_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

Proyecto DSW2 /app/views/implement/edit.html.erb
<%- model_class = Implement -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

Proyecto DSW2 /app/views/implement/index.html.erb
<%- model_class = Implement -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @implements.each do |implement| %>
      <tr>
        <td><%= link_to implement.id, implement_path(implement) %></td>
        <td><%= implement.nombre %></td>
        <td><%=l implement.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_implement_path(implement), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      implement_path(implement),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_implement_path,
            :class => 'btn btn-primary' %>

Proyecto DSW2 /app/views/implement/new.html.erb
<%- model_class = Implement -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

Proyecto DSW2 /app/views/implement/show.html.erb
<%- model_class = Implement -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nombre) %>:</strong></dt>
  <dd><%= @implement.nombre %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              implements_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_implement_path(@implement), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              implement_path(@implement),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>