Proyecto DSW2 /config/routes.rb
Rails.application.routes.draw do
  resources :ingredients
  resources :implements
  resources :recipes do
    resources :comments, only: [:create, :destroy, :update]
  end

  get 'welcome/index'

  devise_for :users
  resources :highs
  get 'search_recipe/index'

  get 'search_recipe/search_form'
  get 'searchrecipe/search'
  get 'searchrecipe/search_form'
  get 'searchrecipe/index'
  get 'searchrecipe/search'
  get 'searchrecipe/search_form'

  root 'welcome#index'

  get "/dashboard", to: "welcome#dashboard"
  get "/aceptarimp", to: "welcome#aceptarimp"
  get "/aceptaring", to: "welcome#aceptaring"

  put "/recipes/:id/publish", to: "recipes#publish"
  put "/implements/:id/publish", to: "implements#publish"
  put "/ingredients/:id/publish", to: "ingredients#publish"

  get "/buscar_receta/index" => "buscar_receta#index"

end

Proyecto DSW2 /app/controllers/search_recipe_controller.rb
class SearchRecipeController < ApplicationController
  def index
	@resultado=Recipe.joins(:ingredients, :implements).where(ingredients: {id: params[:ingredients]}, implements: {id: params[:implements]})
	@resultado=@resultado.uniq
  @resultado=@resultado.where(state: 'published')

    #raise @resultado.to_yaml
  end

  def search_form
      @ingredients = Ingredient.all
      @implements = Implement.all
    
  end
end

Proyecto DSW2 /app/helpers/search_recipe_helper.rb
module SearchRecipeHelper
end

Proyecto DSW2 /app/views/search_recipe/index.html.erb
<%- model_class = Recipe -%>
<div class="page-header">
  <h1>Recetas</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <!--<th><%= model_class.human_attribute_name(:id) %></th> -->
      <th><%= model_class.human_attribute_name(:titulo) %></th>
      <!--<th><%= model_class.human_attribute_name(:dificultad) %></th> -->
      <!--<th><%= model_class.human_attribute_name(:tiempo) %></th> -->
      <!--<th><%= model_class.human_attribute_name(:ingredientes) %></th> -->
      <!--<th><%= model_class.human_attribute_name(:implemento) %></th> -->
      <!--<th><%= model_class.human_attribute_name(:glosa) %></th> -->
      <th><%= model_class.human_attribute_name(:fecha) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  
  <tbody>
    <% @resultado.each do |recipe| %>
      <tr>
        <!--<td><%= link_to recipe.id, recipe_path(recipe) %></td>-->
        <!--<td><%= recipe.titulo %></td> -->
        <!--<td><%= recipe.dificultad %></td> -->
        <!--<td><%= recipe.tiempo %></td> -->
        <!--<td><%= recipe.ingredientes %></td> -->
        <!--<td><%= recipe.implemento %></td> -->
        <!--<td><%= recipe.glosa %></td> -->
        <td><%= link_to recipe.titulo, recipe_path(recipe)%></td>
        <td><%=l recipe.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

Proyecto DSW2 /app/views/search_recipe/search_form.html.erb
<%= form_tag search_recipe_index_path, method: :get do%>
    <label>Ingredients:</label>
    <div style="clear:both"></div>
    <% @ingredients.each do |ingredient| %>
    <div class="field" style="float:left; margin-left:10px">
        <%= check_box_tag "ingredients[]", ingredient.id %> <%= ingredient.nombre %>
    </div>
    <%end%>
    <div style="clear:both"></div>
    <label>Implementos:</label>
    <div style="clear:both"></div>
    <% @implements.each do |implement| %>
    <div class="field" style="float:left; margin-left:10px">
        <%= check_box_tag "implements[]", implement.id %> <%= implement.nombre %>
    </div>
    <%end%>
    
    <div style="clear:both"></div>
    <%= submit_tag "Buscar :)", name: nil, class: "btn btn-primary btn-md" %>
<%end%>