Proyecto DSW2 /config/routes.rb
Rails.application.routes.draw do
  resources :ingredients
  resources :implements
  resources :recipes do
    resources :comments, only: [:create, :destroy, :update]
  end

  get 'welcome/index'

  devise_for :users
  resources :highs
  get 'search_recipe/index'

  get 'search_recipe/search_form'
  get 'searchrecipe/search'
  get 'searchrecipe/search_form'
  get 'searchrecipe/index'
  get 'searchrecipe/search'
  get 'searchrecipe/search_form'

  root 'welcome#index'

  get "/dashboard", to: "welcome#dashboard"
  get "/aceptarimp", to: "welcome#aceptarimp"
  get "/aceptaring", to: "welcome#aceptaring"

  put "/recipes/:id/publish", to: "recipes#publish"
  put "/implements/:id/publish", to: "implements#publish"
  put "/ingredients/:id/publish", to: "ingredients#publish"

  get "/buscar_receta/index" => "buscar_receta#index"

end

Proyecto DSW2 /app/models/recipe.rb
class Recipe < ActiveRecord::Base
    include AASM
    after_create :save_implements
    after_create :save_ingredients
    has_many :recipe_implements, dependent: :destroy
    has_many :recipe_ingredients, dependent: :destroy
    has_many :ingredients, through: :recipe_ingredients
    has_many :implements, through: :recipe_implements
    accepts_nested_attributes_for :ingredients
    accepts_nested_attributes_for :implements 
    has_many :comments   

    belongs_to :user

    scope :aceptadas, ->{where(state: "published")}
    
        #CUSTOM SETTER#
	def ingredients=(value)
            @ingredients = value
	end
	def implements=(value)
            @implements = value
            #raise @implementos.to_yaml
	end
        
        
    aasm column: "state" do
        state :in_draft, initial: true
        state :published

        event :publish do
            transitions from: :in_draft, to: :published
        end

        event :unpublish do
            transitions from: :published, to: :in_draft
        end
    end
    private
        
    #Guarda los implemenos de una receta
    def save_implements
        #raise self.id.to_yaml
        @implements.each do |implement_id|
            recipe_implements.create(implement_id: implement_id, recipe_id: self.id) 
        end
    end
        
    def save_ingredients
        #raise @ingredientes.to_yaml
        @ingredients.each do |ingredient_id|
            recipe_ingredients.create(ingredient_id: ingredient_id, recipe_id: self.id)
        end
                
    end


end

Proyecto DSW2 /app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :authenticate_normal_user!, only: [:create, :new]
  before_action :authenticate_moderador!, only: [:publish]
  before_action :authenticate_admin!, only: [:destroy, :edit, :update]
  before_action :set_recipe, only: [:show, :edit, :update, :destroy, :publish]

  # GET /recipes
  # GET /recipes.json
  def index
    if user_signed_in? && current_user.is_admin? 
      @recipes = Recipe.all
    elsif user_signed_in? && current_user.is_normal_user? 
      @recipes = current_user.recipes.all
    elsif user_signed_in? && current_user.is_moderador?
      @recipes = Recipe.all 
      #@recipes = Recipe.where(:ingredientes => ingredientes)
    else
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @comment = Comment.new
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    @ingredients = Ingredient.aceptados
    @implements = Implement.aceptados
    
  end

  def publish
    @recipe.publish!
    redirect_to @recipe
  end


  # GET /recipes/1/edit
  def edit
    @ingredients = Ingredient.all
    @implements = Implement.all
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = current_user.recipes.new(recipe_params)
    #Asignas los valores de implementos seleccionados a la variable implementos
    @recipe.implements = params[:Implements]
    @recipe.ingredients = params[:Ingredients]
    if params[:Implements].nil? or params[:Ingredients].nil?
      respond_to do |format|
          format.html { redirect_to '/recipes/new', alert: 'Ingrese entre 1 a 10 ingredientes y entre 1 a 5 implementos' }
          format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    elsif params[:Implements].size > 5 or params[:Ingredients].size > 10
      respond_to do |format|
          format.html { redirect_to '/recipes/new', alert: 'Ingrese entre 1 a 10 ingredientes y entre 1 a 5 implementos' }
          format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    
    #Asignas los valores de ingredientes seleccionados a la variable ingredientes
    #@recipe.ingredients = params[:Ingredients]
    #raise params.yaml
      elsif user_signed_in? && current_user.is_normal_user? 
        respond_to do |format|
          if @recipe.save
            format.html { redirect_to @recipe, notice: 'La receta fue creada con exito.' }
            format.json { render :show, status: :created, location: @recipe }
          else
            format.html { render :new }
            format.json { render json: @recipe.errors, status: :unprocessable_entity }
          end 
        end
      else
      respond_to do |format|  
        format.html { redirect_to @recipe, notice: 'No puedes crear Recetas' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    if user_signed_in? && current_user.is_admin? 
      respond_to do |format|
        if @recipe.update(recipe_params)
          format.html { redirect_to @recipe, notice: 'Se ha modificado la receta con exito.' }
          format.json { render :show, status: :ok, location: @recipe }
        else
          format.html { render :edit }
          format.json { render json: @recipe.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to recipes_url, notice: 'No tiene permisos para modificar recetas.' }
        format.json { head :no_content }
      end
    end
  end
  def validate_user
    redirect_to new_user_session_path, notice:"Se necesita iniciar sesion"
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    if user_signed_in? && current_user.is_admin? 
      @recipe.destroy
      respond_to do |format|
        format.html { redirect_to recipes_url, notice: 'Se ha eliminado la receta de forma exitosa.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to recipes_url, notice: 'No se tienen los permisos para eliminar recetas.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:titulo, :dificultad, :tiempo, :Ingredients, :Implements, :glosa)
    end
end

Proyecto DSW2 /app/helpers/recipes_helper.rb
module RecipesHelper
end

Proyecto DSW2 /app/views/recipes/_form.html.erb
<%= form_for @recipe, :html => { :class => "form-horizontal recipe" } do |f| %>

  <% if @recipe.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @recipe.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :titulo, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :titulo, :required => true ,:class => 'form-control' %>
    </div>
    <%=f.error_span(:titulo) %>
  </div>
  <div class="form-group">
    <%= f.label :dificultad, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select( :dificultad,["Facil","Moderado","Dificil"],{},{:required => true, :class => 'form-control'}) %>
    </div>
    <%=f.error_span(:dificultad) %>
  </div>
  <div class="form-group">
    <%= f.label :tiempo, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.time_select  :tiempo, :required => true,:class => 'form-control', :default => {:hour => '00', :minute => '00'} %>
    </div>
    <%=f.error_span(:tiempo) %>
  </div>
  <div class="field" style="margin-left:40px">
    <label> ingredientes </label>
    <br>
    <% @ingredients.each do |ingredient| %>
    <div class="field" style="float:left; margin-left:10px">
      <dd><%= check_box_tag "Ingredients[]", ingredient.id %> <%= ingredient.nombre %></dd>
    </div>
    <% end %>
  </div>
  <div style="clear:both"></div>
  <div class="field" style="margin-left:40px">
    <label> implementos </label>
    <br>
    <% @implements.each do |implement| %>
    <div class="field" style="float:left; margin-left:10px">
      <dd><%= check_box_tag "Implements[]", implement.id %> <%= implement.nombre %></dd>
    </div>
    <% end %>
  </div>
  <br>
  <div style="clear:both"></div>
  <div class="form-group">
    <%= f.label :glosa, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :glosa,:required => true,:rows => 10 ,:class => 'form-control' %>
    </div>
    <%=f.error_span(:glosa) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Solicitar Ingrediente', ingredients_path, :class => 'btn btn-default' %>
      <%= link_to 'Solicitar Implemento', implements_path, :class => 'btn btn-default' %>
      <%= link_to t('.cancelar', :default => t("helpers.links.cancel")),
                recipes_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

Proyecto DSW2 /app/views/recipes/edit.html.erb
ds<%- model_class = Recipe -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

Proyecto DSW2 /app/views/recipes/index.html.erb
<%- model_class = Recipe -%>
<div class="page-header">
  <h1>Recetas</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <!--<th><%= model_class.human_attribute_name(:id) %></th> -->
      <th><%= model_class.human_attribute_name(:titulo) %></th>
      <!--<th><%= model_class.human_attribute_name(:dificultad) %></th> -->
      <!--<th><%= model_class.human_attribute_name(:tiempo) %></th> -->
      <!--<th><%= model_class.human_attribute_name(:ingredientes) %></th> -->
      <!--<th><%= model_class.human_attribute_name(:implemento) %></th> -->
      <!--<th><%= model_class.human_attribute_name(:glosa) %></th> -->
      <th><%= model_class.human_attribute_name(:fecha) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <!--<td><%= link_to recipe.id, recipe_path(recipe) %></td>-->
        <!--<td><%= recipe.titulo %></td> -->
        <!--<td><%= recipe.dificultad %></td> -->
        <!--<td><%= recipe.tiempo %></td> -->
        <!--<td><%= recipe.ingredientes %></td> -->
        <!--<td><%= recipe.implemento %></td> -->
        <!--<td><%= recipe.glosa %></td> -->
        <td><%= link_to recipe.titulo, recipe_path(recipe)%></td>
        <td><%=l recipe.created_at %></td> 
        <td>
          <% if user_signed_in? && current_user.is_moderador? %>
            <%= link_to t('.Editar', :default => t("helpers.links.editar")),
                        edit_recipe_path(recipe), :class => 'btn btn-default btn-xs' %>
          <%end%>
          <% if user_signed_in? && current_user.is_admin? %>
            <%= link_to t('.Eliminar', :default => t("helpers.links.Eliminar")),
                        recipe_path(recipe),

                      :method => :delete,
                      :data => { :confirm => t('.Confirmacion', :default => t("helpers.links.confirmacion", :default => '¿Esta seguro que desea eliminar la receta?')) },
                      :class => 'btn btn-xs btn-danger' %>
          <%end%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if user_signed_in? && current_user.is_normal_user? %>
<%= link_to t('.Crear receta', :default => t("helpers.links.Crear Receta")),
            new_recipe_path,
            :class => 'btn btn-primary' %>
<% end %>

Proyecto DSW2 /app/views/recipes/new.html.erb
<%- model_class = Recipe -%>
<div class="page-header">
  <h1>Nueva Receta</h1>
</div>
<%= render :partial => 'form' %>

Proyecto DSW2 /app/views/recipes/show.html.erb
<%- model_class = Recipe -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:titulo) %>:</strong></dt>
  <dd><%= @recipe.titulo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:dificultad) %>:</strong></dt>
  <dd><%= @recipe.dificultad %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tiempo) %>:</strong></dt>
  <dd><%= @recipe.tiempo.to_s(:time)%></dd>
  <!--Mostrar ingredientes-->
  <div class="field">
    <dt>Ingredientes:</dt>
    <br>
    <% @recipe.ingredients.each do |ingredient| %>

        <dd><%=ingredient.nombre %></dd>
    <%end%>
  </div>
 <!--Mostrar implementos-->
 <div class="field">
    <dt>Implementos:</dt>
    <br>
    <% @recipe.implements.each do |implement| %>
        <dd><%=implement.nombre%></dd>
    <%end%>


  <dt><strong><%= model_class.human_attribute_name(:glosa) %>:</strong></dt>
  <dd><%= simple_format(@recipe.glosa) %></dd>

  <div class="field">
    <h3>Comentarios</h3>
    <br>
    <%= render "comments/form" %>
    <ul>
      <% @recipe.comments.each do |comment| %>
      <li>
        <%= comment.body%> - <%= comment.user.email %>

      </li>
      <%end%>
    </ul>

  </div>

</dl>

<% if user_signed_in? && current_user.is_admin? %>
<%= link_to t('.Atras', :default => t("helpers.links.atras")),
              recipes_path, :class => 'btn btn-default'  %>
<% elsif user_signed_in? && current_user.is_moderador? %>
<%= link_to t('.Atras', :default => t("helpers.links.atras")),
              dashboard_path, :class => 'btn btn-default'  %>  
<% elsif user_signed_in? && current_user.is_normal_user? %>
<%= link_to t('.Atras', :default => t("helpers.links.atras")),
              recipes_path, :class => 'btn btn-default'  %>
<%else%>

<%end%>         
<% if user_signed_in? && current_user.is_admin? %>
  <%= link_to t('.editar', :default => t("helpers.links.editar")),
              edit_recipe_path(@recipe), :class => 'btn btn-default' %>
<%end%>
 <% if user_signed_in? && current_user.is_admin? %>
    <%= link_to t('.Eliminar', :default => t("helpers.links.eliminar")),
              recipe_path(@recipe),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirmacion", :default => '¿Esta seguro que desea eliminar la receta?')) },
              :class => 'btn btn-danger' %>
<%end%>